### ISSUE TITLE
CUDA out of memory with Default Script

### ISSUE THREAD

**Issue by hbb1** [Drexubery/ViewCrafter#36]
Thanks for the great work. I run the default script with an 80GB A100,  but it gives the OOM memory issue.
```python
  sh run_sparse.sh
```

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 39.55 GiB. GPU 0 has a total capacty of 79.10 GiB of which 5.04 GiB is free. Process 232127 has 74.04 GiB memory in use. Of the allocated memory 33.33 GiB is allocated by PyTorch, and 39.47 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Do you know any problem behind this?

**Comment by Drexubery** [comment]
Hello, you can refer to the discussion here https://github.com/Drexubery/ViewCrafter/issues/23#issuecomment-2396131121

**Comment by hbb1** [comment]
Thanks! Using torch 2.4.0 works for me.
